In [2]:
import pandas as pd
import numpy as np

df_hdi = pd.read_excel("worldhdi.xlsx")
df_hdi.head()

,hdi_rank,country,hdi_1990,hdi_2000,hdi_2010,hdi_2015,hdi_2019,hdi_2020,hdi_2021,hdi_2022,rank_change_2015_2022,avg_growth_1990_2000,avg_growth_2000_2010,avg_growth_2010_2022,avg_growth_1990_2022,tier_hdi,iso3c
0,1.0,Switzerland,0.850,0.885,0.940,0.952,0.960,0.957,0.965,0.967,0.0,0.404328,0.604744,0.236267,0.403820,Very High,CHE
1,2.0,Norway,0.845,0.914,0.938,0.952,0.961,0.963,0.964,0.966,-1.0,0.788028,0.259530,0.245416,0.419086,Very High,NOR
2,3.0,Iceland,0.834,0.895,0.927,0.948,0.958,0.955,0.957,0.959,0.0,0.708401,0.351916,0.283213,0.437384,Very High,ISL
3,4.0,"Hong Kong, China (SAR)",0.739,0.831,0.914,0.936,0.953,0.955,0.959,0.956,2.0,1.180229,0.956554,0.375096,0.807808,Very High,HKG
4,5.0,Denmark,0.839,0.890,0.913,0.936,0.946,0.946,0.947,0.952,1.0,0.591852,0.255470,0.349185,0.395638,Very High,DNK

In [3]:
df_jme = pd.read_excel("JME.xlsx")
df_jme.head()

,ISO Code,Country,UN Region,UN Sub Region,SDG Region,Development Regions,UNICEF Region,UNICEF Sub-Regions,WHO Region,World Bank Income Groups,World Bank Income Groups Combined,World Bank Regions
0,AFG,Afghanistan,Asia,Southern Asia,Central Asia and Southern Asia,Least Developed,ROSA,SA,EMRO,Low Income,Low Income,South Asia
1,ALB,Albania,Europe,Southern Europe,Northern America and Europe,More Developed,ECA,EECA,EURO,Upper Middle Income,Middle Income,Europe & Central Asia
2,DZA,Algeria,Africa,Northern Africa,Western Asia and Northern Africa,Less Developed,MENA,MENA,AFRO,Upper Middle Income,Middle Income,Middle East & North Africa
3,AND,Andorra,Europe,Southern Europe,Northern America and Europe,More Developed,ECA,WE,EURO,High Income,High Income,Europe & Central Asia
4,AGO,Angola,Africa,Middle Africa,Sub-Saharan Africa,Least Developed,SSA,ESA,AFRO,Lower Middle Income,Middle Income,Sub-Saharan Africa

In [5]:
df_jme['Country'].unique

<bound method Series.unique of 0      Afghanistan
1          Albania
2          Algeria
3          Andorra
4           Angola
          ...
201       Zimbabwe
202            NaN
203            NaN
204            NaN
205            NaN
Name: Country, Length: 206, dtype: object>

In [6]:
df_jme = df_jme.dropna(subset=['Country'])

In [7]:
df_jme['Country'] = df_jme['Country'].str.strip()

C:\Users\Utilizador\AppData\Local\Temp\ipykernel_325616\3250431399.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_jme['Country'] = df_jme['Country'].str.strip()

In [8]:
countries_ref = df_jme['Country'].unique()

In [9]:
df_hdi_filtered = df_hdi[df_hdi['country'].isin(countries_ref)]

In [10]:
df_hdi_filtered = df_hdi_filtered.rename(columns={'country': 'Country'})

In [11]:
missing = set(df_jme['Country']) - set(df_hdi['country'])
print(missing)

{'The former Yugoslav Republic of Macedonia', 'Holy See', 'Niue', 'Turks and Caicos Islands', 'Montserrat', 'Tokelau', 'British Virgin Islands', 'State of Palestine', 'Turkey', 'United Republic of Tanzania', 'Anguilla', "Democratic People's Republic of Korea", 'Republic of Korea', 'Republic of Moldova', 'Swaziland', 'Democratic Republic of the Congo', 'Cook Islands'}

In [12]:
missing_2 = set(df_hdi['country']) - set(df_jme['Country'])
print(missing_2)

{'Palestine, State of', 'Very high human development', 'Hong Kong, China (SAR)', 'Sub-Saharan Africa', 'Eswatini (Kingdom of)', 'South Asia', 'Organisation for Economic Co-operation and Development', 'Congo (Democratic Republic of the)', 'High human development', 'World', 'Small island developing states', 'Türkiye', 'East Asia and the Pacific', "Korea (Democratic People's Rep. of)", 'Europe and Central Asia', 'Korea (Republic of)', 'Developing countries', 'Latin America and the Caribbean', 'Medium human development', 'Moldova (Republic of)', 'Tanzania (United Republic of)', 'Low human development', 'Arab States', 'North Macedonia', 'Least developed countries'}

In [13]:
country_replace = {
    "Türkiye": "Turkey",
    "Eswatini (Kingdom of)": "Swaziland",
    "Moldova (Republic of)": "Republic of Moldova",
    "Tanzania (United Republic of)": "United Republic of Tanzania",
    "Congo (Democratic Republic of the)": "Democratic Republic of the Congo",
    "Palestine, State of": "State of Palestine",
    "Korea (Republic of)": "Republic of Korea",
    "Korea (Democratic People's Rep. of)": "Democratic People's Republic of Korea",
    "North Macedonia": "The former Yugoslav Republic of Macedonia"
}

df_hdi['country'] = df_hdi['country'].replace(country_replace)

In [14]:
df_jme = df_jme[~df_jme['Country'].isin(missing)]

In [15]:
df_jme = df_jme.dropna(subset=['Country'])
countries_ref = set(df_jme['Country'])

In [16]:
df_hdi_clean = df_hdi[df_hdi['country'].isin(countries_ref)]

In [17]:
set(df_hdi_clean['country']) - countries_ref

set()

In [18]:
countries_ref - set(df_hdi_clean['country'])

set()

In [19]:
df_hdi_clean['country'].nunique()

185

In [20]:
df_hdi_clean['country'].unique()

array(['Switzerland', 'Norway', 'Iceland', 'Denmark', 'Sweden', 'Germany',
       'Ireland', 'Singapore', 'Australia', 'Netherlands', 'Belgium',
       'Finland', 'Liechtenstein', 'United Kingdom', 'New Zealand',
       'United Arab Emirates', 'Canada', 'Luxembourg', 'United States',
       'Austria', 'Slovenia', 'Japan', 'Israel', 'Malta', 'Spain',
       'France', 'Cyprus', 'Italy', 'Estonia', 'Czechia', 'Greece',
       'Bahrain', 'Andorra', 'Poland', 'Latvia', 'Lithuania', 'Croatia',
       'Qatar', 'Saudi Arabia', 'Portugal', 'San Marino', 'Chile',
       'Slovakia', 'Hungary', 'Argentina', 'Kuwait', 'Montenegro',
       'Saint Kitts and Nevis', 'Uruguay', 'Romania',
       'Antigua and Barbuda', 'Brunei Darussalam', 'Russian Federation',
       'Bahamas', 'Panama', 'Oman', 'Georgia', 'Trinidad and Tobago',
       'Barbados', 'Malaysia', 'Costa Rica', 'Serbia', 'Thailand',
       'Kazakhstan', 'Seychelles', 'Belarus', 'Bulgaria', 'Palau',
       'Mauritius', 'Grenada', 'Albania', 'China', 'Armenia', 'Mexico',
       'Iran (Islamic Republic of)', 'Sri Lanka',
       'Bosnia and Herzegovina', 'Saint Vincent and the Grenadines',
       'Dominican Republic', 'Ecuador', 'Cuba', 'Maldives', 'Peru',
       'Azerbaijan', 'Brazil', 'Colombia', 'Libya', 'Algeria',
       'Turkmenistan', 'Guyana', 'Mongolia', 'Dominica', 'Tonga',
       'Jordan', 'Ukraine', 'Tunisia', 'Marshall Islands', 'Paraguay',
       'Fiji', 'Egypt', 'Uzbekistan', 'Viet Nam', 'Saint Lucia',
       'Lebanon', 'South Africa', 'Indonesia', 'Philippines', 'Botswana',
       'Jamaica', 'Samoa', 'Kyrgyzstan', 'Belize',
       'Venezuela (Bolivarian Republic of)',
       'Bolivia (Plurinational State of)', 'Morocco', 'Nauru', 'Gabon',
       'Suriname', 'Bhutan', 'Tajikistan', 'El Salvador', 'Iraq',
       'Bangladesh', 'Nicaragua', 'Cabo Verde', 'Tuvalu',
       'Equatorial Guinea', 'India', 'Micronesia (Federated States of)',
       'Guatemala', 'Kiribati', 'Honduras',
       "Lao People's Democratic Republic", 'Vanuatu',
       'Sao Tome and Principe', 'Namibia', 'Myanmar', 'Ghana', 'Kenya',
       'Nepal', 'Cambodia', 'Congo', 'Angola', 'Cameroon', 'Comoros',
       'Zambia', 'Papua New Guinea', 'Timor-Leste', 'Solomon Islands',
       'Syrian Arab Republic', 'Haiti', 'Uganda', 'Zimbabwe', 'Nigeria',
       'Rwanda', 'Togo', 'Mauritania', 'Pakistan', "Côte d'Ivoire",
       'Lesotho', 'Senegal', 'Sudan', 'Djibouti', 'Malawi', 'Benin',
       'Gambia', 'Eritrea', 'Ethiopia', 'Liberia', 'Madagascar',
       'Guinea-Bissau', 'Guinea', 'Afghanistan', 'Mozambique',
       'Sierra Leone', 'Burkina Faso', 'Yemen', 'Burundi', 'Mali', 'Chad',
       'Niger', 'Central African Republic', 'South Sudan', 'Somalia',
       'Monaco'], dtype=object)

In [21]:
df_hdi.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 210 entries, 0 to 209
Data columns (total 17 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   hdi_rank               193 non-null    float64
 1   country                210 non-null    object
 2   hdi_1990               158 non-null    float64
 3   hdi_2000               191 non-null    float64
 4   hdi_2010               206 non-null    float64
 5   hdi_2015               207 non-null    float64
 6   hdi_2019               207 non-null    float64
 7   hdi_2020               207 non-null    float64
 8   hdi_2021               207 non-null    float64
 9   hdi_2022               208 non-null    float64
 10  rank_change_2015_2022  192 non-null    float64
 11  avg_growth_1990_2000   158 non-null    float64
 12  avg_growth_2000_2010   191 non-null    float64
 13  avg_growth_2010_2022   206 non-null    float64
 14  avg_growth_1990_2022   158 non-null    float64
 15  tier_hdi               208 non-null    object
 16  iso3c                  195 non-null    object
dtypes: float64(14), object(3)
memory usage: 28.0+ KB

In [22]:
df_hdi_clean.info()

<class 'pandas.core.frame.DataFrame'>
Index: 185 entries, 0 to 194
Data columns (total 17 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   hdi_rank               184 non-null    float64
 1   country                185 non-null    object
 2   hdi_1990               136 non-null    float64
 3   hdi_2000               168 non-null    float64
 4   hdi_2010               182 non-null    float64
 5   hdi_2015               183 non-null    float64
 6   hdi_2019               183 non-null    float64
 7   hdi_2020               183 non-null    float64
 8   hdi_2021               183 non-null    float64
 9   hdi_2022               184 non-null    float64
 10  rank_change_2015_2022  183 non-null    float64
 11  avg_growth_1990_2000   136 non-null    float64
 12  avg_growth_2000_2010   168 non-null    float64
 13  avg_growth_2010_2022   182 non-null    float64
 14  avg_growth_1990_2022   136 non-null    float64
 15  tier_hdi               184 non-null    object
 16  iso3c                  185 non-null    object
dtypes: float64(14), object(3)
memory usage: 26.0+ KB

In [23]:
df_hdi_clean.drop(columns=[
    'rank_change_2015_2022',
    'avg_growth_1990_2000',
    'avg_growth_2000_2010',
    'avg_growth_2010_2022',
    'tier_hdi',
    'iso3c'
], inplace=True)

C:\Users\Utilizador\AppData\Local\Temp\ipykernel_325616\914783335.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_hdi_clean.drop(columns=[

In [24]:
df_hdi_clean.info()

<class 'pandas.core.frame.DataFrame'>
Index: 185 entries, 0 to 194
Data columns (total 11 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   hdi_rank              184 non-null    float64
 1   country               185 non-null    object
 2   hdi_1990              136 non-null    float64
 3   hdi_2000              168 non-null    float64
 4   hdi_2010              182 non-null    float64
 5   hdi_2015              183 non-null    float64
 6   hdi_2019              183 non-null    float64
 7   hdi_2020              183 non-null    float64
 8   hdi_2021              183 non-null    float64
 9   hdi_2022              184 non-null    float64
 10  avg_growth_1990_2022  136 non-null    float64
dtypes: float64(10), object(1)
memory usage: 17.3+ KB

In [25]:
df_hdi_clean[df_hdi_clean['hdi_1990'].isna()]['country']

13                        Liechtenstein
22                             Slovenia
34                              Andorra
38                              Croatia
44                             Slovakia
49                           Montenegro
50                Saint Kitts and Nevis
53                  Antigua and Barbuda
58                                 Oman
59                              Georgia
64                               Serbia
67                           Seychelles
68                              Belarus
70                                Palau
72                              Grenada
79               Bosnia and Herzegovina
80     Saint Vincent and the Grenadines
86                             Maldives
88                           Azerbaijan
93                         Turkmenistan
96                             Dominica
101                    Marshall Islands
105                          Uzbekistan
108                             Lebanon
115                               Samoa
121                               Nauru
123                            Suriname
124                              Bhutan
130                          Cabo Verde
132                   Equatorial Guinea
134    Micronesia (Federated States of)
136                            Kiribati
139                             Vanuatu
149                              Angola
151                             Comoros
154                         Timor-Leste
155                     Solomon Islands
160                             Nigeria
170                            Djibouti
174                             Eritrea
175                            Ethiopia
176                             Liberia
177                          Madagascar
178                       Guinea-Bissau
184                        Burkina Faso
188                                Chad
191                         South Sudan
192                             Somalia
194                              Monaco
Name: country, dtype: object

In [27]:
missing = df_hdi_clean.isna().mean()*100
missing.sort_values(ascending=False)

hdi_1990                26.486486
avg_growth_1990_2022    26.486486
hdi_2000                 9.189189
hdi_2010                 1.621622
hdi_2015                 1.081081
hdi_2019                 1.081081
hdi_2020                 1.081081
hdi_2021                 1.081081
hdi_rank                 0.540541
hdi_2022                 0.540541
country                  0.000000
dtype: float64

In [28]:
df_hdi_clean.to_csv("hdi_clean.csv", index=False)